services:
  - type: web
    name: lightchip-lab
    runtime: python
    region: oregon
    plan: starter  # 必须是 starter 或更高
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_NAME
        sync: false
      - key: ADMIN_AFFILIATION
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: PORT
        value: "10000"

    disk:
      - mountPath: /var/data
        name: persistent-data
        sizeGB: 1